In [1]:
import numpy as np


In [2]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [3]:
a = []
size = int(input("Enter the size of the list : "))
for i in range(size):
    val = int(input("Enter the value : "))
    a.append(val)
print(a)
b = np.array(a)
b

Enter the size of the list : 5
Enter the value : 1
Enter the value : 2
Enter the value : 3
Enter the value : 3
Enter the value : 4
[1, 2, 3, 3, 4]


array([1, 2, 3, 3, 4])

In [5]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to check the Dimension and Shape of an array?

In [6]:
print("Dimensions of array :",b.ndim )
print("Shape of array :",b.shape)

Dimensions of array : 2
Shape of array : (3, 3)


# Zeros

In [8]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a.ndim

2

# Ones ==> this function creates an array(either one dimesional or multi dimensional) and fill all the value with one.


In [14]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [15]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a.ndim

2

# Eyes

In [18]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a.shape

(4, 4)

In [22]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# diag ==> This funcrion create a two dimesional array with all the diagonal elements as the given value and rest are zero

In [23]:
a = np.diag([2,4,6,8])
a

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

# randint() ==> This function is used to generate random number in given range randint(min_value,max_vale,total_number)

In [24]:
a = np.random.randint(1,10,20)
a

array([2, 6, 4, 4, 2, 8, 3, 7, 4, 4, 4, 5, 5, 5, 1, 4, 8, 6, 3, 7])

# rand() ==> This function is used to generate random number between 0 to 1

In [25]:
a = np.random.rand(5)
a

array([0.49521998, 0.17626339, 0.45620292, 0.67277042, 0.94306699])

# randn() ==> This function is used to generate a random number to -3 to +3 .This may return positve and negative number

In [26]:
a = np.random.randn(5)
a

array([ 0.4394722 , -1.23233341,  1.92195916,  0.63836643, -0.39826207])

# Reshape

In [27]:
a = np.random.randint(1,100,36)
a

array([32, 88, 78, 87, 85, 18, 34, 23, 33,  6, 73,  9, 30, 52, 89, 27, 72,
       43, 54, 31, 77, 66, 37, 25, 23, 10, 45, 13, 49, 27, 39, 57, 99, 50,
       24, 27])

In [28]:
a.reshape(6,6)

array([[32, 88, 78, 87, 85, 18],
       [34, 23, 33,  6, 73,  9],
       [30, 52, 89, 27, 72, 43],
       [54, 31, 77, 66, 37, 25],
       [23, 10, 45, 13, 49, 27],
       [39, 57, 99, 50, 24, 27]])

In [29]:
a.reshape(9,4)

array([[32, 88, 78, 87],
       [85, 18, 34, 23],
       [33,  6, 73,  9],
       [30, 52, 89, 27],
       [72, 43, 54, 31],
       [77, 66, 37, 25],
       [23, 10, 45, 13],
       [49, 27, 39, 57],
       [99, 50, 24, 27]])

In [30]:
a.reshape(4,9)

array([[32, 88, 78, 87, 85, 18, 34, 23, 33],
       [ 6, 73,  9, 30, 52, 89, 27, 72, 43],
       [54, 31, 77, 66, 37, 25, 23, 10, 45],
       [13, 49, 27, 39, 57, 99, 50, 24, 27]])

In [31]:
a.reshape(18,2)

array([[32, 88],
       [78, 87],
       [85, 18],
       [34, 23],
       [33,  6],
       [73,  9],
       [30, 52],
       [89, 27],
       [72, 43],
       [54, 31],
       [77, 66],
       [37, 25],
       [23, 10],
       [45, 13],
       [49, 27],
       [39, 57],
       [99, 50],
       [24, 27]])

In [32]:
a.reshape(2,18)

array([[32, 88, 78, 87, 85, 18, 34, 23, 33,  6, 73,  9, 30, 52, 89, 27,
        72, 43],
       [54, 31, 77, 66, 37, 25, 23, 10, 45, 13, 49, 27, 39, 57, 99, 50,
        24, 27]])

In [33]:
a.reshape(36,1)

array([[32],
       [88],
       [78],
       [87],
       [85],
       [18],
       [34],
       [23],
       [33],
       [ 6],
       [73],
       [ 9],
       [30],
       [52],
       [89],
       [27],
       [72],
       [43],
       [54],
       [31],
       [77],
       [66],
       [37],
       [25],
       [23],
       [10],
       [45],
       [13],
       [49],
       [27],
       [39],
       [57],
       [99],
       [50],
       [24],
       [27]])

In [34]:
a.reshape(3,12)

array([[32, 88, 78, 87, 85, 18, 34, 23, 33,  6, 73,  9],
       [30, 52, 89, 27, 72, 43, 54, 31, 77, 66, 37, 25],
       [23, 10, 45, 13, 49, 27, 39, 57, 99, 50, 24, 27]])

In [35]:
a.reshape(12,3)

array([[32, 88, 78],
       [87, 85, 18],
       [34, 23, 33],
       [ 6, 73,  9],
       [30, 52, 89],
       [27, 72, 43],
       [54, 31, 77],
       [66, 37, 25],
       [23, 10, 45],
       [13, 49, 27],
       [39, 57, 99],
       [50, 24, 27]])

# Principal of -1

In [39]:
a = a.reshape(-1,4)
a

array([[32, 88, 78, 87],
       [85, 18, 34, 23],
       [33,  6, 73,  9],
       [30, 52, 89, 27],
       [72, 43, 54, 31],
       [77, 66, 37, 25],
       [23, 10, 45, 13],
       [49, 27, 39, 57],
       [99, 50, 24, 27]])

# Seed Function ==> We know that randint function generate random numbers. Everytime we run the program , new set of random number is generated

In [42]:
np.random.seed(12)
a = np.random.randint(1,100,20)
a

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50, 53,  6, 14, 90, 35, 76, 75,
        1, 77, 14])

# View Vs Copy


# View

In [44]:
a = np.array([10,20,30,40,50,60,70])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70])

# Copy

In [46]:
a = np.array([10,20,30,40,50,60,70])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70])

# Conditonal Selection

In [47]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [49]:
a<10


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [51]:
b = a<10
a[b]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [53]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# Operations on Array

In [55]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [56]:
a*2

array([2, 4, 6, 8])

In [57]:
a+2

array([3, 4, 5, 6])

In [58]:
a**2

array([ 1,  4,  9, 16])

In [59]:
a = np.array([10,20,30,40]).reshape(2,2)
a

array([[10, 20],
       [30, 40]])

In [60]:
b = np.array([50,60,70,80]).reshape(2,2)
b

array([[50, 60],
       [70, 80]])

In [61]:
a+b

array([[ 60,  80],
       [100, 120]])

In [62]:
b-a

array([[40, 40],
       [40, 40]])

In [63]:
a*b

array([[ 500, 1200],
       [2100, 3200]])

In [65]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [66]:
b//a

array([[5, 3],
       [2, 2]])

In [67]:
a.dot(b)

array([[1900, 2200],
       [4300, 5000]])

In [68]:
a = np.array([10,20,30,40])
np.min(a)

10

In [69]:
np.max(a)

40

In [70]:
np.argmin(a)

0

In [71]:
np.argmax(a)

3

In [72]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [73]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

# Linspace() ==> This function returns value between a given range and with a same gap between consecutive elements.

In [74]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [76]:
np.random.seed(123)
# a = np.random.randint

# np.unique(arr,return_index = True, return_counts = True)
Returns 3 array 1 the array with unique values. 2. the array with respective index value . 3 . the array with counting of frequency

In [77]:
a = np.array([10,20,30,40,50,20,10])
np.unique(a, return_index = True, return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [78]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [79]:
b

array([5, 6, 7, 8])

In [82]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])