In [ ]:
def selection_sort(arr):
    n = len(arr)

    for i in range(n):
        
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        
        arr[i], arr[min_index] = arr[min_index], arr[i]

    return arr

# Example usage:
my_list = [64, 25, 12, 22, 11]
sorted_list = selection_sort(my_list)

print("Original list:", my_list)
print("Sorted list:", sorted_list)


In [5]:
# take a list and find out the index position of the list

my_list = [10, 20, 30, 100, 50,60,10,3,70]

mindex = 0
mvalue = my_list[0]

for i in range(1, len(my_list)):
    if my_list[i] > mvalue:
        mvalue = my_list[i]
        mindex = i

print(f"The maximum value {mvalue} is at index {mindex}")


The maximum value 100 is at index 3


# Array
Sequential --> Continuous memory

In [2]:
import array as arr

In [10]:
array1 = arr.array('i',[10,20,30,-1])  # (type,values)

In [11]:
array1.append(100)

In [38]:
len(array1)

3

In [30]:
array1[0]

9999

In [14]:
array1

array('i', [9999, 20, 30, -1, 100])

In [15]:
array1.pop()

100

In [16]:
array1.remove(20)

In [17]:
array1

array('i', [9999, 30, -1])

In [18]:
array1[0:2] # slicing in array

array('i', [9999, 30])

In [41]:
ar = arr.array('i',[15,8,20,24,16,30])
ar1 = arr.array('i')
for i in range(len(ar)):
    if i==0 or i==(len(ar)-1):
        if i==0:
            if(ar[i]>ar[i+1]):
                ar1.append(ar[i])
        else:
            if(ar[i]>ar[i-1]):
                ar1.append(ar[i])
    else:
        if (ar[i]>ar[i+1] and ar[i]>ar[i-1]):
              ar1.append(ar[i])
ar1

array('i', [15, 24, 30])

In [42]:
ar = arr.array('i',[6,9,15,8,8,70,20])
ar1 = arr.array('i')
for i in range(len(ar)):
    if i==0 or i==(len(ar)-1):
        if i==0:
            if(ar[i]>ar[i+1]):
                ar1.append(ar[i])
        else:
            if(ar[i]>ar[i-1]):
                ar1.append(ar[i])
    else:
        if (ar[i]>ar[i+1] and ar[i]>ar[i-1]):
              ar1.append(ar[i])
ar1

array('i', [15, 70])

In [39]:
len(ar)

7

In [47]:
# write down a function which take one arguments 

ar = arr.array('i',[10,20,30,40,50,60])
size = (len(ar)-1)
for i in range(len(ar)):
    if i<size:
        ar[i] = ar[size]
        size -=1
ar

array('i', [60, 50, 40, 40, 50, 60])

In [ ]:
def func(array1):
    start = 0
    end = len(array1)-1
    
    while(start<end):
        temp = arr[start]
        arr[start] = arr[end]
        arr[end] = temp
        
        start+=1
        end-=1
        
    return arr
print(array1)

In [52]:
# Take array in function find out the first repetitive number in the array

ar = arr.array('i', [10,20,5,6,20,10])

def func(ar):
    index = len(ar)-1
    for i in range(index):
        if ar[i] == ar[i+1]:
            return ar[i]
        
print(func(ar))

None


In [5]:
# Cylinderical rotation of array
ar = arr.array('i',[10,20,30,40,50])

def right_rotate_array(arr, d):
    n = len(arr)
    d = d % n  

    # Using slicing to perform right rotation
    rotated_array = arr[-d:] + arr[:-d]
    
    return rotated_array

rotation_distance = 1
result = right_rotate_array(ar, rotation_distance)
print("Original Array:", ar)
print("Right Rotated Array:", result)



Original Array: array('i', [10, 20, 30, 40, 50])
Right Rotated Array: array('i', [50, 10, 20, 30, 40])


In [2]:
import numpy as np
arr1 = np.array([1,23,43,53,64])
arr2 = arr1[::-1]

In [3]:
arr2

array([64, 53, 43, 23,  1])

In [7]:
d = {"1":"hell","2":"heelo"}

In [9]:
for k,v in d.items():
    print(k,v)

1 hell
2 heelo


In [15]:
import array as arr
a = arr.array('i',[1,2,3,4,5])

In [11]:
a

array('i', [1, 2, 3, 4, 5])

In [16]:
arr1 = a[::-1]

In [17]:
arr1

array('i', [5, 4, 3, 2, 1])

In [18]:
ar2 = np.array([10,20,30,40])
ar2

array([10, 20, 30, 40])

In [22]:
a3 = np.flip(ar2)

In [23]:
a3

array([40, 30, 20, 10])