In [1]:
a = [10,20,30,40,50]

In [2]:
import numpy as np

In [3]:
a = np.array(a)

In [4]:
a

array([10, 20, 30, 40, 50])

In [5]:
print("Total dimension =",a.ndim)

Total dimension = 1


In [8]:
print("Total Shape =",a.shape)

Total Shape = (5,)


# Pre - defined Functions

In [9]:
# (1). zeore() ==> all values 0

In [11]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [12]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

# (2). Ones() ==> all values 1

In [13]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
a = np.ones((3,4))
a


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# (3). eye() ==> diagonal elements =1 , rest are all = 0
# [[0,0], (1,1), (2,3), (3,3)...(n,n)]


In [16]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
# (4). diag() ==> diagonal position = custom array
a = [1,34,67,99]
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 99]])

In [18]:
# (5). Random Module ==>
# (a). Randint() ==> min_number , max_number , total_numbers

# (b). Rand() ==> total_numbers, limit(0-1)

# (c). Randn() ==> total_numbers , limit(-7 to +7)

# Randint()

In [20]:
a = np.random.randint(1,20,4)
a

array([15, 11, 11,  3])

# Rand()

In [21]:
a = np.random.rand(5)
a

array([0.98461383, 0.87019782, 0.40440552, 0.14639982, 0.51114339])

# Randn()

In [23]:
a = np.random.randn(4)
a

array([-1.41209101,  0.49550932, -0.9251914 , -1.3099997 ])

# How to fix Data?

In [24]:
# table ==> dummy column (random module) ==> model's performance(80-90)

# refresh ==> data update ==> model's performance (40 -50)

# seed()

In [ ]:
np.random.seed(34)
a = np.random.randint()

# Reshaping your data

In [25]:
# n(rows) * n(columns) = n(total_elements)

In [26]:
a = np.random.randint(1,50,12)
a

array([16,  3, 30,  7,  1, 23, 33, 29, 30, 46, 29, 43])

In [27]:
a.reshape(2,6)

array([[16,  3, 30,  7,  1, 23],
       [33, 29, 30, 46, 29, 43]])

In [28]:
a.reshape(3,4)

array([[16,  3, 30,  7],
       [ 1, 23, 33, 29],
       [30, 46, 29, 43]])

In [29]:
a.reshape(6,2)

array([[16,  3],
       [30,  7],
       [ 1, 23],
       [33, 29],
       [30, 46],
       [29, 43]])

# View v/s Copy

In [30]:
a = np.array([10,340,560,78,890])  # Modification is in the original data is called view
a[1:3] = 0
a

array([ 10,   0,   0,  78, 890])

In [32]:
a = np.array([10,340,560,78,890])  # Modification is in the duplicate data the original date is untouched
b = a[1:3].copy()
b[:] = 0
a

array([ 10, 340, 560,  78, 890])

# Conditional Selection

In [33]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [35]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [36]:
b = a<10
a[b]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Operations on array

In [39]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [40]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [41]:
a+b

array([[ 6,  8],
       [10, 12]])

In [42]:
b-a

array([[4, 4],
       [4, 4]])

In [43]:
a*b

array([[ 5, 12],
       [21, 32]])

In [44]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [45]:
a*2

array([[2, 4],
       [6, 8]])

In [46]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

In [47]:
np.min(a)

1

In [48]:
np.max(a)

4

In [49]:
np.argmin(a)

0

In [50]:
np.argmax(a)

3

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [52]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [53]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [54]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [55]:
# Unique() ==>
# (1). uniqe array ==> will not repeat duplicate entries.
# (2). Unique array's ==> original value ondexing number .
# (3). Unique array's frequency ==> Returns frequency of original value .

In [56]:
a = np.array([1,23,45,76,35,34,3,5,356,54224,24,23,23,23,2,329])

In [57]:
np.unique(a , return_index = True, return_counts = True)

(array([    1,     2,     3,     5,    23,    24,    34,    35,    45,
           76,   329,   356, 54224]),
 array([ 0, 14,  6,  7,  1, 10,  5,  4,  2,  3, 15,  8,  9], dtype=int64),
 array([1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

# Horizontal and vertical Stacking

In [58]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [59]:
a

array([1, 2, 3, 4])

In [60]:
b


array([5, 6, 7, 8])

In [61]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
9